### ISSUE TITLE
vagrant up is broken

### ISSUE THREAD

**Issue by exafox** [cfpb/ckan-installer#23]
It is bailing on this provisioning step:

```
TASK: [python27 | installs setuptools] **************************************** 
failed: [default] => {"changed": true, "cmd": ["/usr/local/bin/python2.7", "ez_setup.py"], "delta": "0:00:00.250569", "end": "2016-04-26 12:34:36.272497", "rc": 1, "start": "2016-04-26 12:34:36.021928", "warnings": []}
stderr: Extracting in /tmp/tmpxDbwud
Traceback (most recent call last):
  File "ez_setup.py", line 415, in <module>
    sys.exit(main())
  File "ez_setup.py", line 412, in main
    return _install(archive, _build_install_args(options))
  File "ez_setup.py", line 52, in _install
    with archive_context(archive_filename):
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "ez_setup.py", line 103, in archive_context
    with ContextualZipFile(filename) as archive:
  File "ez_setup.py", line 87, in __new__
    return zipfile.ZipFile(*args, **kwargs)
  File "/usr/local/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file

FATAL: all hosts have already failed -- aborting
```

Suggest we get out of the business of compiling python here and start using this rpm: https://github.com/cfpb/python27-for-el6

**Comment by tanderegg** [comment]
Agreed.  Is it possible to setup a publicly accessible S3 bucket that can mirror our RPM repository?  That would make things like this much easier in general.

**Comment by JeffreyMFarley** [comment]
I had this yesterday.  It turns out there was a [bad push Monday AM](https://github.com/pypa/setuptools/issues/557) to `setuptools` that wasn't correct.  It looks like it might be fixed... check it out now

**Comment by idgserpro** [comment]
The problem wasn't exactly with setuptools, but with changes in pypi structure itself and incompatibilities with ez_setup.py. Check https://github.com/pypa/setuptools/issues/557#issuecomment-214421553 if you want to understand the cause.

To fix your provisioning, you need to use the latest ez_setup.py: in https://github.com/cfpb/ckan-installer/blob/a61f2ee9cb80ef2e6a08897470a46997d179c195/provisioners/roles/python27/tasks/main.yml you're using https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py but you should be using 
https://bootstrap.pypa.io/ez_setup.py instead.

**Comment by tanderegg** [comment]
Thanks @idgserpro, we'll give that a try.

**Comment by exafox** [comment]
Thanks all, vagrant up is working again. Let's track the  RPM usage from a new issue.
